name: Install
description: Install Node.js, pnpm, and dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Install Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version-file: .nvmrc
        cache: 'pnpm'

    - name: Install Dependencies
      shell: bash
      env:
        # Skip Husky installation.
        # See: https://github.com/typicode/husky/blob/ec10d87db/index.js#L9
        HUSKY: '0'
      run: pnpm i
